apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: petclinic-alert
      rules:

        # Pod petclinic absent ou arrêté
        - alert: PodDown
          expr: |
            kube_deployment_status_replicas_available{deployment="petclinic"} == 0
          for: 2m
          labels:
            severity: critical
            team: backend
          annotations:
            summary: "petclinic has no available pod"
            description: "The deployment petclinic has no running pod available for more than 2 minutes."
            runbook_url: "https://wiki/runbooks/petclinic-down"


        # Pod présent mais non Ready
        - alert: PodNotReady
          expr: |
            kube_pod_status_ready{
              namespace="default",
              condition="true",
              pod=~"petclinic-.*"
            } == 0
          for: 2m
          labels:
            severity: critical
            team: backend
          annotations:
            summary: "{{ $labels.pod }} is not ready"
            description: "The pod {{ $labels.pod }} has been not ready for more than 2 minutes."


        # Prometheus ne scrape plus l'application
        - alert: MyAppMetricsMissing
          expr: |
            absent(up{job="petclinic"})
          for: 5m
          labels:
            severity: critical
            team: backend
          annotations:
            summary: "petclinic metrics disappeared"
            description: "Prometheus no longer receives metrics from petclinic."


        # Taux d'erreur HTTP élevé
        - alert: MyAppHighErrorRate
          expr: |
            sum(rate(http_requests_total{job="petclinic", status=~"5.."}[5m]))
            /
            sum(rate(http_requests_total{job="petclinic"}[5m])) > 0.05
          for: 3m
          labels:
            severity: warning
            team: backend
          annotations:
            summary: "Error rate > 5%"
            description: "The application error rate is above 5% for more than 3 minutes."
