apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic

spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: spring-petclinic-monitoring-spring:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: petclinic-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: petclinic-config
              mountPath: /config
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/application.properties"
      volumes:
        - name: petclinic-config
          configMap:
            name: petclinic-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
data:
  application.properties: |
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    management.endpoint.health.probes.enabled=true
    management.health.livenessstate.enabled=true
    management.health.readinessstate.enabled=true

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic-service
spec:
  selector:
    app: petclinic
  type: NodePort
  ports:
    - name: petclinic-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-petclinic
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: petclinic-service
  endpoints:
    - port: petclinic-port
      path: /actuator/prometheus
