name: Terraform deployment

on: workflow_dispatch

env:
  TF_API_TOKEN: "${{ secrets.TF_API_KEY }}"
  ACCESS_KEY: "${{ secrets.ACCESS_KEY }}"
  ORGANIZATION_ID: "${{ secrets.ORGANIZATION_ID }}"
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  SECRET_KEY: "${{ secrets.SECRET_KEY }}"

jobs:
  variable:
    name: Check variable
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Check environment variables
        run: |
          [ -n "$TF_API_TOKEN" ] && echo "TF_API_TOKEN is set" || echo "TF_API_TOKEN is NOT set"
          [ -n "$ACCESS_KEY" ] && echo "ACCESS_KEY is set" || echo "ACCESS_KEY is NOT set"
          [ -n "$ORGANIZATION_ID" ] && echo "ORGANIZATION_ID is set" || echo "ORGANIZATION_ID is NOT set"
          [ -n "$PROJECT_ID" ] && echo "PROJECT_ID is set" || echo "PROJECT_ID is NOT set"
          [ -n "$SECRET_KEY" ] && echo "SECRET_KEY is set" || echo "SECRET_KEY is NOT set"

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"
      - name: Terraform init
        working-directory: infrastructure/terraform
        run: | 
          terraform init
      - name: Terraform plan
        working-directory: infrastructure/terraform
        run: |
          terraform plan
      - name: Terraform apply
        working-directory: infrastructure/terraform
        run: |
          terraform apply -auto-approve
        



        
        


