name: Terraform destroy

on: workflow_dispatch

jobs:
  terraform:
    name: destroy
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"
      - name: Destroy
        working-directory:  infrastructure/terraform
        run: |
          terraform destroy -auto-approve
          
          
          
  
    
