name: Terraform deployment

on: workflow_dispatch

env:
  TF_VAR_API_TOKEN: "${{ secrets.TF_API_KEY }}"
  TF_VAR_access_key: "${{ secrets.ACCESS_KEY }}"
  TF_VAR_organization_id: "${{ secrets.ORGANIZATION_ID }}"
  TF_VAR_project_id: "${{ secrets.PROJECT_ID }}"
  TF_VAR_secret_key: "${{ secrets.SECRET_KEY }}"

jobs:
  variable:
    name: Check variables
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Check environment variables
        run: |
          [ -n "$TF_VAR_API_TOKEN" ] && echo "TF_API_TOKEN is set" || echo "TF_API_TOKEN is NOT set"
          [ -n "$TF_VAR_access_key" ] && echo "ACCESS_KEY is set" || echo "ACCESS_KEY is NOT set"
          [ -n "$TF_VAR_organization_id" ] && echo "ORGANIZATION_ID is set" || echo "ORGANIZATION_ID is NOT set"
          [ -n "$TF_VAR_project_id" ] && echo "PROJECT_ID is set" || echo "PROJECT_ID is NOT set"
          [ -n "$TF_VAR_secret_key" ] && echo "SECRET_KEY is set" || echo "SECRET_KEY is NOT set"

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: env

    outputs:
      kubeconfig: ${{ steps.terraform-output.outputs.kubeconfig }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"

      - name: Terraform init
        working-directory: infrastructure/terraform
        run: |
          terraform init \
          -backend-config="access_key=${{ secrets.ACCESS_KEY }}"\
          -backend-config="secret_key=${{ secrets.SECRET_KEY }}"

      - name: Terraform plan
        working-directory: infrastructure/terraform
        run: terraform plan

      - name: Terraform apply
        working-directory: infrastructure/terraform
        run: terraform apply -auto-approve

      - name: Get Terraform kubeconfig
        id: terraform-output
        working-directory: infrastructure/terraform
        run: |
          kubeconfig=$(terraform output -raw kubeconfig)
          echo "::add-mask::$kubeconfig"

          {
            echo "kubeconfig<<EOF"
            echo "$kubeconfig"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

  kubernetes_deploy:
    name: Kubernetes
    needs: [terraform]
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        env:
          KUBECONFIG_CONTENT: ${{ needs.terraform.outputs.kubeconfig }}
        run: |
          mkdir -p "$HOME/.kube"

          printf '%s\n' "$KUBECONFIG_CONTENT" > "$HOME/.kube/config"

          chmod 600 "$HOME/.kube/config"

      - name: Check Kubernetes cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy
        working-directory: infrastructure/kubernetes
        run: |
          kubectl apply -f .

      - name: Check deployment
        run: |
          kubectl get pods
          kubectl get services
